// authentication actions
export const SIGN_IN_INIT = "SIGN_IN_INIT";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
export const REQUEST_LIST_SUCCESS = "REQUEST_LIST_SUCCESS";
export const REQUEST_LIST_COUNT_SUCCESS = "REQUEST_LIST_COUNT_SUCCESS";
export const REQUEST_LIST_FAIL = "REQUEST_LIST_FAIL";
export const REQUEST_LIST_COUNT_FAIL = "REQUEST_LIST_COUNT_FAIL";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_IN_INIT = "REFRESH_TOKEN_IN_INIT";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";
export const SOMETHINGWENTWRONG = "SOMETHINGWENTWRONG";
export const SOMETHINGWENTWRONGREMOVE = "SOMETHINGWENTWRONGREMOVE";
export const SAVE_USER_BY_SECURITY_ADMIN_SUCCESS =
  "SAVE_USER_BY_SECURITY_ADMIN_SUCCESS";
export const SAVE_USER_BY_SECURITY_ADMIN_FAIL =
  "SAVE_USER_BY_SECURITY_ADMIN_FAIL";
export const REJECT_USER_BY_SECURITY_ADMIN_SUCCESS =
  "REJECT_USER_BY_SECURITY_ADMIN_SUCCESS";
export const REJECT_USER_BY_SECURITY_ADMIN_FAIL =
  "REJECT_USER_BY_SECURITY_ADMIN_FAIL";
export const SAVE_USER_BY_SECURITY_LIST_INIT =
  "SAVE_USER_BY_SECURITY_LIST_INIT";
export const REJECT_USER_BY_SECURITY_LIST_INIT =
  "REJECT_USER_BY_SECURITY_LIST_INIT";
export const GET_ALL_USER_DATA_INIT = "GET_ALL_USER_DATA_INIT";
export const GET_ALL_USER_DATA_SUCCESS = "GET_ALL_USER_DATA_SUCCESS";
export const GET_ALL_USER_DATA_FAIL = "GET_ALL_USER_DATA_FAIL";
export const EDIT_USER_INIT = "EDIT_USER_INIT";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";


//NOTIFICATIONs
export const NOTIFICATION = "NOTIFICATION";
export const FIND_CUSTOMER_FROM_MISYS_INIT = "FIND_CUSTOMER_FROM_MISYS_INIT";
export const RESET_STATE = "RESET_STATE";
export const FIND_CUSTOMER_FROM_MISYS_SUCCESS =
  "FIND_CUSTOMER_FROM_MISYS_SUCCESS";
export const FIND_CUSTOMER_FROM_MISYS_FAIL = "FIND_CUSTOMER_FROM_MISYS_FAIL";
export const FIND_CUSTOMER_ACCOUNT_DETAILS_FROM_MYSIS_INIT =
  "FIND_CUSTOMER_ACCOUNT_DETAILS_FROM_MYSIS_INIT";
export const FIND_CUSTOMER_ACCOUNT_DETAILS_FROM_MYSIS_SUCCESS =
  "FIND_CUSTOMER_ACCOUNT_DETAILS_FROM_MYSIS_SUCCESS";
export const FIND_CUSTOMER_ACCOUNT_DETAILS_FROM_MYSIS_FAIL =
  "FIND_CUSTOMER_ACCOUNT_DETAILS_FROM_MYSIS_FAIL";
export const ADD_WRITE_OFF_INIT = "ADD_WRITE_OFF_INIT";
export const ADD_WRITE_OFF_SUCCESS = "ADD_WRITE_OFF_SUCESS";
export const ADD_WRITE_OFF_FAIL = "ADD_WRITE_OFF_FAIL";

//approvalscount
export const GET_APPROVALS_COUNT_INIT = "GET_APPROVALS_COUNT_INIT";
export const GET_APPROVALS_COUNT_SUCCESS = "GET_APPROVALS_COUNT_SUCCESS";
export const GET_APPROVALS_COUNT_FAIL = "GET_APPROVALS_COUNT_FAIL";
export const SAVE_USER_REQUEST_SUCCESS = "SAVE_USER_REQUEST_SUCCESS";
export const SAVE_USER_REQUEST_FAIL = "SAVE_USER_REQUEST_FAIL";

//approvals
export const GET_APPROVALS_INIT = "GET_APPROVALS_INIT";
export const GET_APPROVALS_SUCCESS = "GET_APPROVALS_SUCCESS";
export const GET_APPROVALS_FAIL = "GET_APPROVALS_FAIL";

//Save approvals
export const SAVE_APPROVALS_INIT = "SAVE_APPROVALS_INIT";
export const SAVE_APPROVALS_SUCCESS = "SAVE_APPROVALS_SUCCESS";
export const SAVE_APPROVALS_FAIL = "SAVE_APPROVALS_FAIL";

//view write off
export const VIEW_WRITE_OFF_INIT = "VIEW_WRITE_OFF_INIT";
export const VIEW_WRITE_OFF_SUCCESS = "VIEW_WRITE_OFF_SUCCESS";
export const VIEW_WRITE_OFF_FAIL = "VIEW_WRITE_OFF_FAIL";
export const NULL_STATE = "NULL_STATE";
//listofwriteoff
export const LIST_WRITE_OFF_INIT = "LIST_WRITE_OFF_INIT";
export const LIST_WRITE_OFF_SUCCESS = "LIST_WRITE_OFF_SUCCESS";
export const LIST_WRITE_OFF_FAIL = "LIST_WRITE_OFF_FAIL";
//Editofwriteoff
export const EDIT_WRITE_OFF_INIT = "EDIT_WRITE_OFF_INIT";
export const EDIT_WRITE_OFF_SUCCESS = "EDIT_WRITE_OFF_SUCCESS";
export const EDIT_WRITE_OFF_FAIL = "EDIT_WRITE_OFF_FAIL";
//Deleteofwriteoff
export const DELETE_WRITE_OFF_INIT = "DELETE_WRITE_OFF_INIT";
export const DELETE_WRITE_OFF_SUCCESS = "DELETE_WRITE_OFF_SUCCESS";
export const DELETE_WRITE_OFF_FAIL = "DELETE_WRITE_OFF_FAIL";

//view approvals
export const VIEW_APPROVAL_HISTORY_INIT = "VIEW_APPROVAL_HISTORY_INIT";
export const VIEW_APPROVAL_HISTORY_SUCCESS = "VIEW_APPROVAL_HISTORY_SUCCESS";
export const VIEW_APPROVAL_HISTORY_FAIL = "VIEW_APPROVAL_HISTORY_FAIL";

// complete report

export const COMPLETE_REPORT_INIT = "COMPLETE_REPORT_INIT";
export const COMPLETE_REPORT_SUCCESS = "COMPLETE_REPORT_SUCCESS";
export const COMPLETE_REPORT_FAIL = "COMPLETE_REPORT_FAIL";

// credit policy report

export const CREDIT_POLICY_REPORT_INIT = "CREDIT_POLICY_REPORT_INIT";
export const CREDIT_POLICY_REPORT_SUCCESS = "CREDIT_POLICY_REPORT_SUCCESS";
export const CREDIT_POLICY_REPORT_FAIL = "CREDIT_POLICY_REPORT_FAIL";

// balance sheet report

export const BALANCE_SHEET_REPORT_INIT = "BALANCE_SHEET_REPORT_INIT";
export const BALANCE_SHEET_REPORT_SUCCESS = "BALANCE_SHEET_REPORT_SUCCESS";
export const BALANCE_SHEET_REPORT_FAIL = "BALANCE_SHEET_REPORT_FAIL";

// UI
export const UI_GO_BACK_ENABLE = "UI_GO_BACK_ENABLE";
export const UI_GO_BACK_DISABLE = "UI_GO_BACK_DISABLE";
export const HIDE = "HIDE";
export const SHOW = "SHOW";

// SETUP FORMS ACTION TYPES:
export const GET_SETUP_FORM_INIT = "GET_SETUP_FORM_INIT";
export const GET_SETUP_FORM_FAIL = "GET_SETUP_FORM_FAIL";
export const GET_BORROWER_TYPE_INIT = "GET_BORROWER_TYPE_INIT";
export const GET_BORROWER_TYPE_SUCCESS = "GET_BORROWER_TYPE_SUCCESS";
export const GET_BORROWER_TYPE_FAIL = "GET_BORROWER_TYPE_FAIL";

export const ADD_BORROWER_TYPE_INIT = "ADD_BORROWER_TYPE_INIT";
export const ADD_BORROWER_TYPE_SUCCESS = "ADD_BORROWER_TYPE_SUCCESS";
export const ADD_BORROWER_TYPE_FAIL = "ADD_BORROWER_TYPE_FAIL";

export const UPDATE_BORROWER_TYPE_INIT = "UPDATE_BORROWER_TYPE_INIT";
export const UPDATE_BORROWER_TYPE_SUCCESS = "UPDATE_BORROWER_TYPE_SUCCESS";
export const UPDATE_BORROWER_TYPE_FAIL = "UPDATE_BORROWER_TYPE_FAIL";

export const DELETE_BORROWER_TYPE_INIT = "DELETE_BORROWER_TYPE_INIT";
export const DELETE_BORROWER_TYPE_SUCCESS = "DELETE_BORROWER_TYPE_SUCCESS";
export const DELETE_BORROWER_TYPE_FAIL = "DELETE_BORROWER_TYPE_FAIL";

export const GET_ADVANCE_CLASSIFICATION_INIT =
  "GET_ADVANCE_CLASSIFICATION_INIT";
export const GET_ADVANCE_CLASSIFICATION_SUCCESS =
  "GET_ADVANCE_CLASSIFICATION_SUCCESS";
export const GET_ADVANCE_CLASSIFICATION_FAIL =
  "GET_ADVANCE_CLASSIFICATION_FAIL";

export const ADD_ADVANCE_CLASSIFICATION_INIT =
  "ADD_ADVANCE_CLASSIFICATION_INIT";
export const ADD_ADVANCE_CLASSIFICATION_SUCCESS =
  "ADD_ADVANCE_CLASSIFICATION_SUCCESS";
export const ADD_ADVANCE_CLASSIFICATION_FAIL =
  "ADD_ADVANCE_CLASSIFICATION_FAIL";

export const UPDATE_ADVANCE_CLASSIFICATION_INIT =
  "UPDATE_ADVANCE_CLASSIFICATION_INIT";
export const UPDATE_ADVANCE_CLASSIFICATION_SUCCESS =
  "UPDATE_ADVANCE_CLASSIFICATION_SUCCESS";
export const UPDATE_ADVANCE_CLASSIFICATION_FAIL =
  "UPDATE_ADVANCE_CLASSIFICATION_FAIL";

export const DELETE_ADVANCE_CLASSIFICATION_INIT =
  "DELETE_ADVANCE_CLASSIFICATION_INIT";
export const DELETE_ADVANCE_CLASSIFICATION_SUCCESS =
  "DELETE_ADVANCE_CLASSIFICATION_SUCCESS";
export const DELETE_ADVANCE_CLASSIFICATION_FAIL =
  "DELETE_ADVANCE_CLASSIFICATION_FAIL";

export const GET_MANAGEMENT_UNIT_INIT = "GET_MANAGEMENT_UNIT_INIT";
export const GET_MANAGEMENT_UNIT_SUCCESS = "GET_MANAGEMENT_UNIT_SUCCESS";
export const GET_MANAGEMENT_UNIT_FAIL = "GET_MANAGEMENT_UNIT_FAIL";

export const ADD_MANAGEMENT_UNIT_INIT = "ADD_MANAGEMENT_UNIT_INIT";
export const ADD_MANAGEMENT_UNIT_SUCCESS = "ADD_MANAGEMENT_UNIT_SUCCESS";
export const ADD_MANAGEMENT_UNIT_FAIL = "ADD_MANAGEMENT_UNIT_FAIL";

export const UPDATE_MANAGEMENT_UNIT_INIT = "UPDATE_MANAGEMENT_UNIT_INIT";
export const UPDATE_MANAGEMENT_UNIT_SUCCESS = "UPDATE_MANAGEMENT_UNIT_SUCCESS";
export const UPDATE_MANAGEMENT_UNIT_FAIL = "UPDATE_MANAGEMENT_UNIT_FAIL";

export const DELETE_MANAGEMENT_UNIT_INIT = "DELETE_MANAGEMENT_UNIT_INIT";
export const DELETE_MANAGEMENT_UNIT_SUCCESS = "DELETE_MANAGEMENT_UNIT_SUCCESS";
export const DELETE_MANAGEMENT_UNIT_FAIL = "DELETE_MANAGEMENT_UNIT_FAIL";

export const GET_NATURE_OF_CHARGE_INIT = "GET_NATURE_OF_CHARGE_INIT";
export const GET_NATURE_OF_CHARGE_SUCCESS = "GET_NATURE_OF_CHARGE_SUCCESS";
export const GET_NATURE_OF_CHARGE_DELETE = "GET_NATURE_OF_CHARGE_DELETE";

export const GET_NATURE_OF_SECURITY_INIT = "GET_NATURE_OF_SECURITY_INIT";
export const GET_NATURE_OF_SECURITY_SUCCESS = "GET_NATURE_OF_SECURITY_SUCCESS";
export const GET_NATURE_OF_SECURITY_DELETE = "GET_NATURE_OF_SECURITY_DELETE";

export const GET_WRITEOFFREASON_INIT = "GET_WRITEOFFREASON_INIT";
export const GET_WRITEOFFREASON_SUCCESS = "GET_WRITEOFFREASON_SUCCESS";
export const GET_WRITEOFFREASON_DELETE = "GET_WRITEOFFREASON_DELETE";

export const GET_APPROVAL_REASON_INIT = "GET_APPROVAL_REASON_INIT";
export const GET_APPROVAL_REASON_SUCCESS = "GET_APPROVAL_REASON_SUCCESS";
export const GET_APPROVAL_REASON_FAIL = "GET_APPROVAL_REASON_FAIL";

export const GET_REJECTION_REASON_INIT = "GET_REJECTION_REASON_INIT";
export const GET_REJECTION_REASON_SUCCESS = "GET_REJECTION_REASON_SUCCESS";
export const GET_REJECTION_REASON_FAIL = "GET_REJECTION_REASON_FAIL";

export const GET_APPROVAL_FLOW_INIT = "GET_APPROVAL_FLOW_INIT";
export const GET_APPROVAL_FLOW_SUCCESS = "GET_APPROVAL_FLOW_SUCCESS";
export const GET_APPROVAL_FLOW_FAIL = "GET_APPROVAL_FLOW_FAIL";

export const GET_APPROVAL_FLOW_FOR_EDIT_SUCCESS =
  "GET_APPROVAL_FLOW_FOR_EDIT_SUCCESS";
export const ACTIONS_APPROVAL_FLOW_FOR_EDIT_SUCCESS =
  "ACTIONS_APPROVAL_FLOW_FOR_EDIT_SUCCESS";
export const DOWNLOAD_EXCEL_FILE_INIT = "DOWNLOAD_EXCEL_FILE_INIT";
export const DOWNLOAD_EXCEL_FILE_SUCESS = "DOWNLOAD_EXCEL_FILE_SUCCESS";
export const DOWNLOAD_EXCEL_FILE_FAIL = "DOWNLOAD_EXCEL_FILE_FAIL";

export const LIST_OFF_PENDING_AND_APPROVED_CASES_SUCCESS =
  "LIST_OFF_PENDING_AND_APPROVED_CASES_SUCCESS";
export const LIST_OFF_PENDING_AND_APPROVED_CASES_FAIL =
  "LIST_OFF_PENDING_AND_APPROVED_CASES_FAIL";

export const ACTIVE_EDIT = "ACTIVE_EDIT";
export const ACTIVE_TAB = "ACTIVE_TAB";
export const CLOSED_TAB = "CLOSED_TAB";

export const ROUTING_DATA = "ROUTING_DATA";

export const LOADER_TRUE = "LOADER_TRUE";

export const LOADER_REPORT = "LOADER_REPORT";



